# 02_0930 R程式語言入門

> 請先確認領取作業assignment002，並在Rstudio建立作業複本專案

## 認識R Studio介面

`Console`: R語言終端視窗
`Source`: R腳本, Rmarkdown編輯視窗

## 測試R Studio功能

開啟作業複本專案內的"FIG2-1.Rmd"，跟著教練的示範操作。


## 函式與參數

```
function(argument1, argument2, ...)
```

## 練習1 與 練習2

開啟作業複本專案內的“Assignment.Rmd”，按照教練的解說練習。


## 參數預設名稱

比較電子書2.0.7程式碼的執行結果。


## Rstudio編寫程式碼技巧

使用“Assignment.Rmd"，**技巧測試**這段的R chunk測試電子書2.0.8展示的技巧

## 瀏覽packages

跟著教練查看已經有的packages

`base`常用函式[速查表](files/base-r-TC.pdf)


```
套件(package)類似手機作業系統
函式(function)類以手機應用程式
```


## 安裝套件 

如果packages裡沒有`tidyverse`，再由`Console`執行電子書2.0.10的指令

## 匯入套件

仼何R腳本,Rmarkdown文件檔一開始要執行匯入需要套件的函式

Rmarkdown文件檔應匯入的套件應放在開頭的``` setup ``` chunk

## 升級套件

遇到版本不相容的訊息時，需要重新執行安裝套件函式。  

許多套件說明文件會提供維持最新版本的建議操作。


## 函式名稱衝突

在`Console`測試電子書2.0.13的指令。

## 物件(Objects)

R的所有物件以指派運算子`<-`宣告。例如"FIG2-1.Rmd"裡的`x`與`y`。

統計分析的變項(variable)在R環境中，是以物件處理。變項/物件通常是統計分析函式的參數。


## 演練物件處理

使用“Assignment.Rmd"，**練習5**這段的R chunk測試電子書2.0.15展示的程式碼

<!--- 首先在討論區回應**測試結果**的前五位同學，採計本次作業**演練活用度**評分。 --->

## 清理不需要的物件

從`Console`清理

從"Environment"清理


## Rsutdio後台設定

請跟著教練觀看最新版本設定介面


## 執行緒(sessions)

Rmarkdown chunk將所有函式與物件堆疊於執行緒，累積太多會拖慢執行速度。編輯工作到一段落需要做一次**重啟**。

**查看方式** 在`Console`執行`sessionInfo()`

參考電子書2.0.19進行**重啟**。


## 引用R與Rstudio貢獻者資訊

配合“Assignment.Rmd"**練習6**進行課後演練。

APA文內引用範例: R語言核心開發團隊[@R-base]; Rstudio核心開發團隊[@Rstudiocoreteam]

## 取得更多幫助資訊

教練的經驗分享。

配合“Assignment.Rmd"**練習7**，下課後尋找幫助資訊解決這道問題。


### 參考文獻
